// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/grpc/alert_query/v1/alert_query.proto

package alertqueryv1

import (
	"context"

	"google.golang.org/grpc"
)

// AlertQueryServiceServer is the server API for AlertQueryService.
type AlertQueryServiceServer interface {
	QueryHistory(context.Context, *AlertQuery) (*QueryHistoryResponse, error)
	ListActive(context.Context, *ListActiveRequest) (*ListActiveResponse, error)
}

// UnimplementedAlertQueryServiceServer can be embedded.
type UnimplementedAlertQueryServiceServer struct{}

func (UnimplementedAlertQueryServiceServer) QueryHistory(context.Context, *AlertQuery) (*QueryHistoryResponse, error) {
	return nil, nil
}
func (UnimplementedAlertQueryServiceServer) ListActive(context.Context, *ListActiveRequest) (*ListActiveResponse, error) {
	return nil, nil
}

// AlertQueryServiceClient is the client API for AlertQueryService.
type AlertQueryServiceClient interface {
	QueryHistory(ctx context.Context, in *AlertQuery, opts ...grpc.CallOption) (*QueryHistoryResponse, error)
	ListActive(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error)
}

type alertQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertQueryServiceClient(cc grpc.ClientConnInterface) AlertQueryServiceClient {
	return &alertQueryServiceClient{cc}
}

func (c *alertQueryServiceClient) QueryHistory(ctx context.Context, in *AlertQuery, opts ...grpc.CallOption) (*QueryHistoryResponse, error) {
	out := new(QueryHistoryResponse)
	err := c.cc.Invoke(ctx, "alert_query.v1.AlertQueryService/QueryHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertQueryServiceClient) ListActive(ctx context.Context, in *ListActiveRequest, opts ...grpc.CallOption) (*ListActiveResponse, error) {
	out := new(ListActiveResponse)
	err := c.cc.Invoke(ctx, "alert_query.v1.AlertQueryService/ListActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertQueryService_ServiceDesc is the grpc.ServiceDesc for AlertQueryService.
var AlertQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert_query.v1.AlertQueryService",
	HandlerType: (*AlertQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryHistory",
			Handler:    _AlertQueryService_QueryHistory_Handler,
		},
		{
			MethodName: "ListActive",
			Handler:    _AlertQueryService_ListActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/alert_query/v1/alert_query.proto",
}

func _AlertQueryService_QueryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertQueryServiceServer).QueryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "alert_query.v1.AlertQueryService/QueryHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertQueryServiceServer).QueryHistory(ctx, req.(*AlertQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertQueryService_ListActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertQueryServiceServer).ListActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "alert_query.v1.AlertQueryService/ListActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertQueryServiceServer).ListActive(ctx, req.(*ListActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterAlertQueryServiceServer registers an AlertQueryService implementation.
func RegisterAlertQueryServiceServer(s grpc.ServiceRegistrar, srv AlertQueryServiceServer) {
	s.RegisterService(&AlertQueryService_ServiceDesc, srv)
}
