// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc/alert_query/v1/alert_query.proto

package alertqueryv1

import (
	alertv1 "github.com/rainbrookx/hazard-chem-position-alert/api/grpc/alert/v1"
)

// AlertQuery 告警查询过滤条件
type AlertQuery struct {
	Types       []alertv1.AlertType `protobuf:"varint,1,rep,packed,name=types,enum=alert.v1.AlertType" json:"types,omitempty"`
	StartTimeMs int64               `protobuf:"varint,2,opt,name=start_time_ms,json=startTimeMs" json:"start_time_ms,omitempty"`
	EndTimeMs   int64               `protobuf:"varint,3,opt,name=end_time_ms,json=endTimeMs" json:"end_time_ms,omitempty"`
	ZoneId      string              `protobuf:"bytes,4,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Limit       int32               `protobuf:"varint,5,opt,name=limit" json:"limit,omitempty"`
	Offset      int32               `protobuf:"varint,6,opt,name=offset" json:"offset,omitempty"`
}

// AlertRecord 告警记录（查询结果）
type AlertRecord struct {
	Event       *alertv1.AlertEvent `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	CreatedAtMs int64               `protobuf:"varint,2,opt,name=created_at_ms,json=createdAtMs" json:"created_at_ms,omitempty"`
}

// ActiveAlert 活跃告警摘要
type ActiveAlert struct {
	AlertId       string            `protobuf:"bytes,1,opt,name=alert_id,json=alertId" json:"alert_id,omitempty"`
	AlertType     alertv1.AlertType `protobuf:"varint,2,opt,name=alert_type,json=alertType,enum=alert.v1.AlertType" json:"alert_type,omitempty"`
	Severity      alertv1.Severity  `protobuf:"varint,3,opt,name=severity,enum=alert.v1.Severity" json:"severity,omitempty"`
	TriggerTimeMs int64             `protobuf:"varint,4,opt,name=trigger_time_ms,json=triggerTimeMs" json:"trigger_time_ms,omitempty"`
	PersonIds     []string          `protobuf:"bytes,5,rep,name=person_ids,json=personIds" json:"person_ids,omitempty"`
	ZoneId        string            `protobuf:"bytes,6,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Description   string            `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
}

type QueryHistoryResponse struct {
	Records []*AlertRecord `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	Total   int32          `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
}

type ListActiveRequest struct {
	Types []alertv1.AlertType `protobuf:"varint,1,rep,packed,name=types,enum=alert.v1.AlertType" json:"types,omitempty"`
}

type ListActiveResponse struct {
	Alerts []*ActiveAlert `protobuf:"bytes,1,rep,name=alerts" json:"alerts,omitempty"`
}
