// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/grpc/alert/v1/alert.proto

package alertv1

import (
	"context"

	"google.golang.org/grpc"
)

// AlertEvent 告警事件消息（gRPC 推送 payload）
type AlertEvent struct {
	AlertId       string    `protobuf:"bytes,1,opt,name=alert_id,json=alertId" json:"alert_id,omitempty"`
	AlertType     AlertType `protobuf:"varint,2,opt,name=alert_type,json=alertType,enum=alert.v1.AlertType" json:"alert_type,omitempty"`
	Severity      Severity  `protobuf:"varint,3,opt,name=severity,enum=alert.v1.Severity" json:"severity,omitempty"`
	TriggerTimeMs int64     `protobuf:"varint,4,opt,name=trigger_time_ms,json=triggerTimeMs" json:"trigger_time_ms,omitempty"`
	PersonIds     []string  `protobuf:"bytes,5,rep,name=person_ids,json=personIds" json:"person_ids,omitempty"`
	X             float64   `protobuf:"fixed64,6,opt,name=x" json:"x,omitempty"`
	Y             float64   `protobuf:"fixed64,7,opt,name=y" json:"y,omitempty"`
	ZoneId        string    `protobuf:"bytes,8,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	RuleId        string    `protobuf:"bytes,9,opt,name=rule_id,json=ruleId" json:"rule_id,omitempty"`
	Description   string    `protobuf:"bytes,10,opt,name=description" json:"description,omitempty"`
}

type SubscribeRequest struct {
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
}

// AlertPushServiceServer is the server API for AlertPushService.
type AlertPushServiceServer interface {
	// SubscribeAlerts Data Preprocessor 调用此 RPC 建立告警推送流
	SubscribeAlerts(*SubscribeRequest, grpc.ServerStreamingServer[AlertEvent]) error
}

// UnimplementedAlertPushServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAlertPushServiceServer struct{}

func (UnimplementedAlertPushServiceServer) SubscribeAlerts(*SubscribeRequest, grpc.ServerStreamingServer[AlertEvent]) error {
	return nil
}

// AlertPushServiceClient is the client API for AlertPushService.
type AlertPushServiceClient interface {
	SubscribeAlerts(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertEvent], error)
}

type alertPushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertPushServiceClient(cc grpc.ClientConnInterface) AlertPushServiceClient {
	return &alertPushServiceClient{cc}
}

func (c *alertPushServiceClient) SubscribeAlerts(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AlertEvent], error) {
	stream, err := c.cc.NewStream(ctx, &AlertPushService_ServiceDesc.Streams[0], "alert.v1.AlertPushService/SubscribeAlerts", opts...)
	if err != nil {
		return nil, err
	}
	x := &alertPushServiceSubscribeAlertsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type alertPushServiceSubscribeAlertsClient struct {
	grpc.ClientStream
}

func (x *alertPushServiceSubscribeAlertsClient) Recv() (*AlertEvent, error) {
	m := new(AlertEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AlertPushService_ServiceDesc is the grpc.ServiceDesc for AlertPushService.
var AlertPushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert.v1.AlertPushService",
	HandlerType: (*AlertPushServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAlerts",
			Handler:       _AlertPushService_SubscribeAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/grpc/alert/v1/alert.proto",
}

func _AlertPushService_SubscribeAlerts_Handler(srv any, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlertPushServiceServer).SubscribeAlerts(m, &alertPushServiceSubscribeAlertsServer{stream})
}

type alertPushServiceSubscribeAlertsServer struct {
	grpc.ServerStream
}

func (x *alertPushServiceSubscribeAlertsServer) Send(m *AlertEvent) error {
	return x.ServerStream.SendMsg(m)
}

// RegisterAlertPushServiceServer registers a service implementation.
func RegisterAlertPushServiceServer(s grpc.ServiceRegistrar, srv AlertPushServiceServer) {
	s.RegisterService(&AlertPushService_ServiceDesc, srv)
}
