// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc/alert/v1/alert.proto

package alertv1

// AlertType 告警类型枚举
type AlertType int32

const (
	AlertType_ALERT_TYPE_UNSPECIFIED   AlertType = 0
	AlertType_ALERT_TYPE_BOUNDARY      AlertType = 1 // 越界报警
	AlertType_ALERT_TYPE_STATIONARY    AlertType = 2 // 静止报警
	AlertType_ALERT_TYPE_OVERCROWDING  AlertType = 3 // 超员报警
	AlertType_ALERT_TYPE_UNDERSTAFFING AlertType = 4 // 缺员报警
	AlertType_ALERT_TYPE_LOITERING     AlertType = 5 // 滞留报警
	AlertType_ALERT_TYPE_ONEKEY        AlertType = 6 // 一键报警
	AlertType_ALERT_TYPE_GATHERING     AlertType = 7 // 人员聚集预警
	AlertType_ALERT_TYPE_SYSTEM        AlertType = 8 // 系统告警（配置缺失、内部错误等）
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0: "ALERT_TYPE_UNSPECIFIED",
		1: "ALERT_TYPE_BOUNDARY",
		2: "ALERT_TYPE_STATIONARY",
		3: "ALERT_TYPE_OVERCROWDING",
		4: "ALERT_TYPE_UNDERSTAFFING",
		5: "ALERT_TYPE_LOITERING",
		6: "ALERT_TYPE_ONEKEY",
		7: "ALERT_TYPE_GATHERING",
		8: "ALERT_TYPE_SYSTEM",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNSPECIFIED":   0,
		"ALERT_TYPE_BOUNDARY":      1,
		"ALERT_TYPE_STATIONARY":    2,
		"ALERT_TYPE_OVERCROWDING":  3,
		"ALERT_TYPE_UNDERSTAFFING": 4,
		"ALERT_TYPE_LOITERING":     5,
		"ALERT_TYPE_ONEKEY":        6,
		"ALERT_TYPE_GATHERING":     7,
		"ALERT_TYPE_SYSTEM":        8,
	}
)

func (x AlertType) String() string {
	if name, ok := AlertType_name[int32(x)]; ok {
		return name
	}
	return "ALERT_TYPE_UNSPECIFIED"
}

// Severity 严重级别
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_YELLOW      Severity = 1 // 黄色预警（聚集 3 人）
	Severity_SEVERITY_ORANGE      Severity = 2 // 橙色预警（聚集 4-6 人）
	Severity_SEVERITY_RED         Severity = 3 // 红色预警（聚集 >6 人）/ 越界 / 一键报警等
)

var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_YELLOW",
		2: "SEVERITY_ORANGE",
		3: "SEVERITY_RED",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_YELLOW":      1,
		"SEVERITY_ORANGE":      2,
		"SEVERITY_RED":         3,
	}
)

func (x Severity) String() string {
	if name, ok := Severity_name[int32(x)]; ok {
		return name
	}
	return "SEVERITY_UNSPECIFIED"
}
