// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/grpc/fence/v1/fence.proto

package fencev1

// FenceSource 围栏数据来源
type FenceSource int32

const (
	FenceSource_SOURCE_UNSPECIFIED FenceSource = 0
	FenceSource_SOURCE_EXTERNAL    FenceSource = 1 // 第三方系统经 Data Preprocessor 同步
	FenceSource_SOURCE_LOCAL       FenceSource = 2 // 本项目 Web 页面本地新增/修改
)

var (
	FenceSource_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "SOURCE_EXTERNAL",
		2: "SOURCE_LOCAL",
	}
	FenceSource_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"SOURCE_EXTERNAL":    1,
		"SOURCE_LOCAL":       2,
	}
)

func (x FenceSource) String() string {
	if name, ok := FenceSource_name[int32(x)]; ok {
		return name
	}
	return "SOURCE_UNSPECIFIED"
}

// GeofenceType 围栏类型
type GeofenceType int32

const (
	GeofenceType_GEOFENCE_TYPE_UNSPECIFIED GeofenceType = 0
	GeofenceType_GEOFENCE_TYPE_FORBIDDEN   GeofenceType = 1 // 禁止进入
	GeofenceType_GEOFENCE_TYPE_RESTRICTED  GeofenceType = 2 // 受限区域
	GeofenceType_GEOFENCE_TYPE_SAFE        GeofenceType = 3 // 安全区域
)

var (
	GeofenceType_name = map[int32]string{
		0: "GEOFENCE_TYPE_UNSPECIFIED",
		1: "GEOFENCE_TYPE_FORBIDDEN",
		2: "GEOFENCE_TYPE_RESTRICTED",
		3: "GEOFENCE_TYPE_SAFE",
	}
	GeofenceType_value = map[string]int32{
		"GEOFENCE_TYPE_UNSPECIFIED": 0,
		"GEOFENCE_TYPE_FORBIDDEN":   1,
		"GEOFENCE_TYPE_RESTRICTED":  2,
		"GEOFENCE_TYPE_SAFE":        3,
	}
)

func (x GeofenceType) String() string {
	if name, ok := GeofenceType_name[int32(x)]; ok {
		return name
	}
	return "GEOFENCE_TYPE_UNSPECIFIED"
}

// Point 二维坐标点
type Point struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

// Geofence 电子围栏定义 (protobuf)
type Geofence struct {
	ZoneId                    string       `protobuf:"bytes,1,opt,name=zone_id,json=zoneId" json:"zone_id,omitempty"`
	Name                      string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type                      GeofenceType `protobuf:"varint,3,opt,name=type,enum=fence.v1.GeofenceType" json:"type,omitempty"`
	Vertices                  []*Point     `protobuf:"bytes,4,rep,name=vertices" json:"vertices,omitempty"`
	MaxPeople                 int32        `protobuf:"varint,5,opt,name=max_people,json=maxPeople" json:"max_people,omitempty"`
	MinPeople                 int32        `protobuf:"varint,6,opt,name=min_people,json=minPeople" json:"min_people,omitempty"`
	MaxStaySeconds            int32        `protobuf:"varint,7,opt,name=max_stay_seconds,json=maxStaySeconds" json:"max_stay_seconds,omitempty"`
	StationarySeconds         int32        `protobuf:"varint,8,opt,name=stationary_seconds,json=stationarySeconds" json:"stationary_seconds,omitempty"`
	StationaryThresholdMeters float64      `protobuf:"fixed64,9,opt,name=stationary_threshold_meters,json=stationaryThresholdMeters" json:"stationary_threshold_meters,omitempty"`
	StationaryRecoverySeconds int32        `protobuf:"varint,10,opt,name=stationary_recovery_seconds,json=stationaryRecoverySeconds" json:"stationary_recovery_seconds,omitempty"`
	RequiredPersonIds         []string     `protobuf:"bytes,11,rep,name=required_person_ids,json=requiredPersonIds" json:"required_person_ids,omitempty"`
	GridCellMeters            int32        `protobuf:"varint,12,opt,name=grid_cell_meters,json=gridCellMeters" json:"grid_cell_meters,omitempty"`
	IsActive                  bool         `protobuf:"varint,13,opt,name=is_active,json=isActive" json:"is_active,omitempty"`
	Source                    FenceSource  `protobuf:"varint,14,opt,name=source,enum=fence.v1.FenceSource" json:"source,omitempty"`
}

type PullAllFencesRequest struct {
	EngineId string `protobuf:"bytes,1,opt,name=engine_id,json=engineId" json:"engine_id,omitempty"`
}

type PullAllFencesResponse struct {
	Fences  []*Geofence `protobuf:"bytes,1,rep,name=fences" json:"fences,omitempty"`
	Version int64       `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
}

type NotifyFenceChangeRequest struct {
	EngineId      string `protobuf:"bytes,1,opt,name=engine_id,json=engineId" json:"engine_id,omitempty"`
	NewVersion    int64  `protobuf:"varint,2,opt,name=new_version,json=newVersion" json:"new_version,omitempty"`
	ChangedZoneId string `protobuf:"bytes,3,opt,name=changed_zone_id,json=changedZoneId" json:"changed_zone_id,omitempty"`
}

type NotifyFenceChangeResponse struct {
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged" json:"acknowledged,omitempty"`
}
