// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/grpc/fence/v1/fence.proto

package fencev1

import (
	"context"

	"google.golang.org/grpc"
)

// FenceSyncServiceServer is the server API for FenceSyncService (Data Preprocessor side).
type FenceSyncServiceServer interface {
	PullAllFences(context.Context, *PullAllFencesRequest) (*PullAllFencesResponse, error)
	NotifyFenceChange(context.Context, *NotifyFenceChangeRequest) (*NotifyFenceChangeResponse, error)
}

// UnimplementedFenceSyncServiceServer can be embedded.
type UnimplementedFenceSyncServiceServer struct{}

func (UnimplementedFenceSyncServiceServer) PullAllFences(context.Context, *PullAllFencesRequest) (*PullAllFencesResponse, error) {
	return nil, nil
}
func (UnimplementedFenceSyncServiceServer) NotifyFenceChange(context.Context, *NotifyFenceChangeRequest) (*NotifyFenceChangeResponse, error) {
	return nil, nil
}

// FenceSyncServiceClient is the client API for FenceSyncService (Alert Engine side).
type FenceSyncServiceClient interface {
	PullAllFences(ctx context.Context, in *PullAllFencesRequest, opts ...grpc.CallOption) (*PullAllFencesResponse, error)
	NotifyFenceChange(ctx context.Context, in *NotifyFenceChangeRequest, opts ...grpc.CallOption) (*NotifyFenceChangeResponse, error)
}

type fenceSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFenceSyncServiceClient(cc grpc.ClientConnInterface) FenceSyncServiceClient {
	return &fenceSyncServiceClient{cc}
}

func (c *fenceSyncServiceClient) PullAllFences(ctx context.Context, in *PullAllFencesRequest, opts ...grpc.CallOption) (*PullAllFencesResponse, error) {
	out := new(PullAllFencesResponse)
	err := c.cc.Invoke(ctx, "fence.v1.FenceSyncService/PullAllFences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fenceSyncServiceClient) NotifyFenceChange(ctx context.Context, in *NotifyFenceChangeRequest, opts ...grpc.CallOption) (*NotifyFenceChangeResponse, error) {
	out := new(NotifyFenceChangeResponse)
	err := c.cc.Invoke(ctx, "fence.v1.FenceSyncService/NotifyFenceChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FenceSyncService_ServiceDesc is the grpc.ServiceDesc for FenceSyncService.
var FenceSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fence.v1.FenceSyncService",
	HandlerType: (*FenceSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullAllFences",
			Handler:    _FenceSyncService_PullAllFences_Handler,
		},
		{
			MethodName: "NotifyFenceChange",
			Handler:    _FenceSyncService_NotifyFenceChange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/fence/v1/fence.proto",
}

func _FenceSyncService_PullAllFences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullAllFencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceSyncServiceServer).PullAllFences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "fence.v1.FenceSyncService/PullAllFences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceSyncServiceServer).PullAllFences(ctx, req.(*PullAllFencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FenceSyncService_NotifyFenceChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyFenceChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FenceSyncServiceServer).NotifyFenceChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "fence.v1.FenceSyncService/NotifyFenceChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FenceSyncServiceServer).NotifyFenceChange(ctx, req.(*NotifyFenceChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterFenceSyncServiceServer registers a FenceSyncService implementation.
func RegisterFenceSyncServiceServer(s grpc.ServiceRegistrar, srv FenceSyncServiceServer) {
	s.RegisterService(&FenceSyncService_ServiceDesc, srv)
}
